language: go

go:
  - 1.7

before_install:
  - git config --global url."http://github.com/".insteadOf "https://github.com/"
  - go get -t -v ./...

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)